spring:
  application:
    name: realtime-chat

  data:
    mongodb:
      uri: mongodb://${MONGO_ROOT_USER:admin}:${MONGO_ROOT_PASSWORD:password}@localhost:27017/chat_db?authSource=admin
      auto-index-creation: true

    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    org.springframework.web.socket: WARN
    io.github.pedrozaz.chatserver: DEBUG

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:d7ff2b31dd6cfc62fc735f26f49659a742b6d36b14a140693ff25021c00e66f5}
    expiration: 86400000